#!/usr/bin/env python3
"""Convert the question bank spreadsheet into the data file the website loads.

Usage:
    python3 scripts/build_questions.py [input.xlsx] [output.js]

Defaults: data/questions.xlsx -> assets/questions.js

Every sheet whose header row starts with "م" is treated as one regulation.
Expected columns (in order):
    م | النظام | المستوى | نمط السؤال | نص السؤال | الخيارات | الإجابة الصحيحة |
    السند النظامي ذو الارتباط | شرح مبسط | ملاحظات للمراجعة

Options are written one per line inside the "الخيارات" cell, and the
"الإجابة الصحيحة" cell must match one of them exactly. The review-notes
column is internal and is never published.
"""

import json
import re
import sys
from pathlib import Path

try:
    import openpyxl
except ImportError:
    sys.exit("openpyxl is required: pip install openpyxl")

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_IN = ROOT / "data" / "questions.xlsx"
DEFAULT_OUT = ROOT / "assets" / "questions.js"

LEVELS = [
    (1, "الأول (تأسيسي)", ("الأول", "تأسيسي")),
    (2, "المتوسط", ("المتوسط",)),
    (3, "المتقدم", ("المتقدم",)),
]

TYPES = [
    ("tf", "صح/خطأ", ("صح", "خطأ")),
    ("exclude", "استبعاد الخيار الخاطئ", ("استبعاد",)),
    ("mcq", "اختيار من متعدد", ("اختيار",)),
]


def clean(value):
    if value is None:
        return ""
    text = str(value).replace("\r\n", "\n").replace("\r", "\n")
    return re.sub(r"[ \t ]+", " ", text).strip()


def match(value, table, what, where):
    for key, _label, needles in table:
        if any(n in value for n in needles):
            return key
    raise ValueError(f"{where}: unknown {what} '{value}'")


def system_name(raw, fallback):
    # "1- نظام الكهرباء" -> "نظام الكهرباء"
    name = re.sub(r"^\s*\d+\s*[-–.)]\s*", "", raw or "").strip()
    return name or fallback


def build(src):
    wb = openpyxl.load_workbook(src, data_only=True)
    systems, errors = [], []

    for ws in wb.worksheets:
        rows = list(ws.iter_rows(values_only=True))
        if not rows or clean(rows[0][0]) != "م":
            continue  # instructions sheet or anything else without the header

        questions, raw_system = [], ""
        for row_no, row in enumerate(rows[1:], start=2):
            cells = [clean(v) for v in (list(row) + [None] * 10)[:10]]
            num, sys_raw, level, qtype, text, options, answer, ref, expl, _notes = cells
            if not text:
                continue
            where = f"[{ws.title}] row {row_no}"
            raw_system = raw_system or sys_raw
            try:
                level_key = match(level, LEVELS, "level", where)
                type_key = match(qtype, TYPES, "question type", where)
            except ValueError as exc:
                errors.append(str(exc))
                continue

            opts = [o.strip() for o in options.split("\n") if o.strip()]
            if type_key == "tf" and not opts:
                opts = ["صح", "خطأ"]
            if len(opts) < 2:
                errors.append(f"{where}: needs at least two options")
                continue
            if answer not in opts:
                errors.append(f"{where}: correct answer '{answer}' is not one of the options")
                continue

            questions.append({
                "id": f"{len(systems) + 1}-{num or row_no}",
                "n": num,
                "level": level_key,
                "type": type_key,
                "text": text,
                "options": opts,
                "answer": opts.index(answer),
                "reference": ref,
                "explanation": expl,
            })

        if questions:
            systems.append({
                "id": len(systems) + 1,
                "name": system_name(raw_system, ws.title),
                "short": ws.title.strip(),
                "questions": questions,
            })

    if errors:
        raise SystemExit("Spreadsheet problems:\n  " + "\n  ".join(errors))
    if not systems:
        raise SystemExit("No question sheets found (header row must start with 'م').")

    return {
        "levels": {str(k): label for k, label, _ in LEVELS},
        "systems": systems,
    }


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_IN
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT
    data = build(src)
    body = json.dumps(data, ensure_ascii=False, indent=1)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "// Generated by scripts/build_questions.py from data/questions.xlsx — do not edit by hand.\n"
        f"window.QUIZ_DATA = {body};\n",
        encoding="utf-8",
    )
    total = sum(len(s["questions"]) for s in data["systems"])
    print(f"Wrote {out.relative_to(ROOT) if out.is_relative_to(ROOT) else out}: "
          f"{len(data['systems'])} regulations, {total} questions")


if __name__ == "__main__":
    main()
